---
# tasks file for ansible-pacemaker
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: config.yml
  tags:
    - pacemaker_config

- include_tasks: cluster.yml
  tags:
    - pacemaker_cluster
